sudo: required

services:
  - docker

language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  - DOCKER_IMAGE=baraba123/breakout:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"